name: Release

on:
  push:
    tags:
    - '*.*.*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK 6.0
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: '6.0.x'

      - name: Run release.sh
        run: ./cicd/test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          XPTO: "abcd"
